const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Inject a `installer.pods_project.targets.each ... uniq!` block into the
 * Podfile's post_install hook.
 *
 * Background
 * ----------
 * `withDeduplicateBuildPhases` (run as a withXcodeProject plugin)
 * deduplicates phases in the main app's pbxproj
 * (`ios/Sortlist.xcodeproj/project.pbxproj`). But the duplicate
 * `[CP-User] [Hermes] Replace Hermes for the right configuration, if needed`
 * phase that's killing EAS Build is in the PODS project
 * (`ios/Pods/Pods.xcodeproj/project.pbxproj`), which CocoaPods generates
 * fresh on every `pod install` and which `withXcodeProject` can't touch.
 *
 * Only a Podfile `post_install` Ruby block runs inside CocoaPods'
 * installer context with access to `installer.pods_project.targets`.
 * This plugin patches the autogenerated Podfile to inject that block
 * immediately after `react_native_post_install(installer)`, so RN's
 * own post-install hook runs first, then our dedup runs and collapses
 * any duplicates RN (or another pod's script_phase) introduced.
 *
 * Idempotent: the patch is skipped if the marker comment is already in
 * the Podfile.
 *
 * Must be the LAST plugin in app.json so it runs after every other
 * plugin (no plugin downstream of this one modifies the Podfile).
 */
const MARKER = '# withPodfilePatch: dedupe Pods build phases';

module.exports = function withPodfilePatch(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile',
      );
      if (!fs.existsSync(podfilePath)) {
        console.warn(
          '[withPodfilePatch] Podfile not found at ' + podfilePath + '; ' +
            'skipping. (Are you running prebuild without iOS support?)',
        );
        return config;
      }

      let podfile = fs.readFileSync(podfilePath, 'utf8');
      if (podfile.includes(MARKER)) {
        return config; // already patched
      }

      const dedupBlock = `
    ${MARKER}
    installer.pods_project.targets.each do |target|
      target.build_phases.uniq! { |p| p.display_name }
    end`;

      const anchor = 'react_native_post_install(installer)';
      if (!podfile.includes(anchor)) {
        console.warn(
          '[withPodfilePatch] anchor "' + anchor + '" not found in Podfile; ' +
            "the Podfile's post_install shape has changed and the patch " +
            "wasn't applied. EAS Build may still error on duplicate phases.",
        );
        return config;
      }

      podfile = podfile.replace(anchor, `${anchor}${dedupBlock}`);

      fs.writeFileSync(podfilePath, podfile);
      console.info(
        '[withPodfilePatch] injected Pods-project build-phase dedup into Podfile post_install',
      );
      return config;
    },
  ]);
};
